name: First workflow
on: workflow_dispatch # when should the workflow get triggered
jobs:
  first-job:
    runs-on: macos-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!!"
      - name: Print goodbye
        run: echo "Done - bye!"
